/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productinformation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class listproducts extends javax.swing.JFrame {

    Connection con;
    Statement st;
    PreparedStatement pst;
    ResultSet rs;
   
    public listproducts() {
        initComponents();
        getListProducts("SELECT * FROM company_products");
    }
    
     public Connection openConnection(){
    if(con == null){
    String url = "jdbc:mysql://localhost/";
    String dbName = "productinformation";
    String driver = "com.mysql.jdbc.Driver";
    String userName = "root";
    String password = "";

try{
Class.forName(driver);
this.con = (Connection) DriverManager.getConnection(url+dbName, userName, password);

System.out.println("Connection Successful");

}catch(ClassNotFoundException | SQLException sqle){
System.out.println("Connection Failed!\n"+sqle+"");
}
}

return con;

    }
     
      public void getListProducts(String qry){

try{

pst = openConnection().prepareStatement(qry);
rs = pst.executeQuery();
DefaultTableModel tm = (DefaultTableModel)product_table.getModel();
tm.setColumnIdentifiers(new Object[]{"ID", "Name", "Brand", "Price","Availability", "Category"});
tm.setRowCount(0);

while(rs.next()){
Object obj[] = {rs.getInt("ID"), rs.getString("product_name"), rs.getString("product_brand"), rs.getString("product_price"), rs.getString("product_qty"), rs.getString("product_category")};
tm.addRow(obj);
}

}catch(SQLException e){
System.out.println(e);
}

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        product_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        product_price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        product_qty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        product_category = new javax.swing.JComboBox<>();
        product_brand = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("SYSTEM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 320, 180, 40);

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("INFORMATION");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 270, 260, 40);

        jLabel10.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("PRODUCT");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(100, 220, 170, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 350, 680);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRODUCT NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 440, 230, 40);
        jPanel1.add(product_name);
        product_name.setBounds(400, 480, 230, 40);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRODUCT PRICE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(710, 340, 230, 40);
        jPanel1.add(product_price);
        product_price.setBounds(710, 380, 230, 40);

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("AVAILABLE  QTY.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(710, 440, 230, 40);
        jPanel1.add(product_qty);
        product_qty.setBounds(710, 480, 230, 40);

        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        product_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(product_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 0, 670, 310);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PRODUCT ID");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(400, 340, 230, 40);

        ID.setEditable(false);
        jPanel1.add(ID);
        ID.setBounds(400, 380, 230, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/join-background.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(344, -6, 660, 670);

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setLayout(null);

        product_category.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        product_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a category", "Drinks", "Gadgets", "Foods", "T-shirts", "Cosmetics", "Appliances", "Shoes", "Bicycles", " " }));
        jPanel3.add(product_category);
        product_category.setBounds(730, 50, 230, 40);
        jPanel3.add(product_brand);
        product_brand.setBounds(400, 50, 230, 40);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CATEGORY");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(730, 10, 230, 40);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PRODUCT BRAND");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(400, 10, 230, 40);

        back.setBackground(new java.awt.Color(255, 255, 51));
        back.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.PNG"))); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back);
        back.setBounds(20, 50, 130, 50);

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/join-background.jpg"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, -10, 1010, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new HOME().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void product_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_tableMouseClicked
        int index = product_table.getSelectedRow();        
        TableModel model = product_table.getModel();
        ID.setText(model.getValueAt(index,0).toString());

        product_name.setText(model.getValueAt(index,1).toString());



        product_brand.setText(model.getValueAt(index,2).toString());
        product_price.setText(model.getValueAt(index,3).toString());
        product_qty.setText(model.getValueAt(index,4).toString());
        product_category.setSelectedItem(model.getValueAt(index,5).toString()); 
    }//GEN-LAST:event_product_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listproducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField product_brand;
    private javax.swing.JComboBox<String> product_category;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField product_price;
    private javax.swing.JTextField product_qty;
    private javax.swing.JTable product_table;
    // End of variables declaration//GEN-END:variables
}
